### ISSUE TITLE
Milestone 1 Comment

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/525_group_3#16]
Missing Team-work contract in canvas submission (-10)

Good job with the rest of assignment!

**Comment by Glenn032787** [comment]
Feel free to send me your teamwork contract on slack or in this issue to receive the mark!

**Comment by Glenn032787** [comment]
@AguilarRaul sent me the teamwork contract over slack. I have given you the marks!

**Comment by samson-bakos** [comment]
Thanks Glenn! Very strange as I definitely commented it, but thank you for giving the marks with manual submission
